exclude: "docs|frontend/node_modules|frontend/.next|frontend/out|.git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config=backend/setup.cfg", "--max-complexity=10"]
        additional_dependencies:
          [
            flake8-isort,
            flake8-pytest,
            flake8-pytest-style,
            flake8-bandit,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-string-format,
            flake8-bugbear,
            flake8-debugger,
            flake8-eradicate,
            flake8-broken-line,
            pep8-naming,
            darglint,
            mccabe,
          ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: ["--ignore-path=frontend/.prettierignore"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args: ["--max-warnings=0", "--ext=ts", "--ext=tsx", "--ext=js"]
        additional_dependencies:
          [
            eslint@v7.32.0,
            eslint-plugin-react,
            eslint-plugin-react-hooks,
            eslint-plugin-jsx-a11y,
          ]
