version: "3.8"

services:
  web:
    build:
      context: .
      cache_from:
        - ${BACKEND_IMAGE:-improved_cloud_selection_backend}:latest
      dockerfile: ./Dockerfile.prod
    image: ${BACKEND_IMAGE:-improved_cloud_selection_backend}:latest
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - PORT=8000
      - REDIS_URL=redis://redis:6380
      - FRONTEND_URL=http://localhost:3001

  redis:
    image: redis:6.2
    container_name: redis
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
