version: "3.8"

services:
  web:
    build: .
    command: poetry run gunicorn --bind 0.0.0.0:8000 improved_cloud_selection.main:app -k uvicorn.workers.UvicornWorker
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=prod
      - TESTING=0
