version: "3.8"

services:
  web:
    build: .
    image: improved_cloud_selection_backend:dev
    command: poetry run uvicorn improved_cloud_selection.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      # The IP address of Elysee in Paris
      # This is needed because the backend can't have access to the
      # remote IP address while being sent requests from localhost
      - OVERRIDE_USER_IP=194.5.172.19

  redis:
    image: redis:6.2
    container_name: redis
