[tool.poetry]
name = "improved-cloud-selection"
version = "0.1.0"
description = ""
authors = ["Roman Mkrtchian <mkrtchia@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.1"
uvicorn = "^0.15.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
requests = "^2.26.0"
pytest-cov = "^2.12.1"
flake8 = "^3.9.2"
black = "^21.9b0"
isort = "^5.9.3"
pytest-xdist = "^2.3.0"
